;---------4 PROGRAMLI LED ANIMASYON------------------------
	LIST	P=16F877A
	INCLUDE	"P16F877A.INC"
	__CONFIG	_WDT_OFF & _LVP_OFF & _CP_OFF & _XT_OSC
CBLOCK		H'20'
	DELAY1,DELAY2,GECIK1,GECIK2
	ENDC	
	BSF		STATUS,5
	CLRF	TRISB	
	BSF		TRISA,0
	MOVLW	H'06'
	MOVWF	ADCON1
	BCF		STATUS,5
	CLRF	PORTB
	BCF		STATUS,C
;ANA PROGRAM
LED_SABIT
	BTFSC	PORTA,0
	GOTO	$-1	
	CALL	BUTONARK
LED_SABITT
	BTFSS	PORTA,0
	GOTO	$-1
	MOVLW	H'FF'
	MOVWF	PORTB
LED_KHIGHTRIDER
	BTFSC	PORTA,0
	GOTO	$-1	
	CALL	BUTONARK
	BTFSS	PORTA,0
	GOTO	$-1
	MOVLW	H'01'
	MOVWF	PORTB
	;BSF		STATUS,C; BURADA OLURSA LED ARTARAK GÝDER 	
SOL	
	CALL	ZAMAN_0
	RLF		PORTB,F
	BTFSC	PORTA,0
	GOTO	$+2
	GOTO	LED_ANIM
	BTFSS	STATUS,C
	GOTO	SOL
SAG
	CALL	ZAMAN_0
	RRF		PORTB,F
	BTFSC	PORTA,0
	GOTO	$+2

	GOTO	LED_ANIM
	BTFSS	STATUS,C
	GOTO	SAG
	GOTO	SOL
LED_ANIM
	CALL	ZAMAN_0
	MOVLW	B'10000001'
	MOVWF	PORTB
	CALL	ZAMAN_01
	MOVLW	B'11000011'
	MOVWF	PORTB
	CALL	ZAMAN_01
	MOVLW	B'11100111'
	MOVWF	PORTB
	CALL	ZAMAN_01
	MOVLW	B'11111111'
	MOVWF	PORTB
LED_SWAP
	BTFSC	PORTA,0
	GOTO	LED_ANIM
ZAMAN_00
	MOVLW	H'FF'
	MOVWF	DELAY1
D11
	MOVLW	H'FF'
	MOVWF	DELAY2
D22
	DECFSZ	DELAY2,F
	GOTO	D22
	DECFSZ	DELAY1,F
	GOTO	D11
	MOVLW	H'0F'		;ilk swap
	MOVWF	PORTB
	BTFSC	PORTA,0	
	GOTO	ZAMAN_000
	BTFSS	PORTA,0
	GOTO	$-1
	GOTO	LED_SABITT
ZAMAN_000
	MOVLW	H'FF'
	MOVWF	DELAY1
D111
	MOVLW	H'FF'
	MOVWF	DELAY2
D222
	DECFSZ	DELAY2,F
	GOTO	D222
	DECFSZ	DELAY1,F
	GOTO	D111		
	MOVLW	H'F0'		;SON swap
	MOVWF	PORTB
	BTFSC	PORTA,0	
	GOTO	ZAMAN_00
	BTFSS	PORTA,0
	GOTO	$-1
	GOTO	LED_SABITT
ZAMAN_01
	BTFSC	PORTA,0
	GOTO	$+4
	BTFSS	PORTA,0
	GOTO	$-1
	GOTO	ZAMAN_00
ZAMAN_0
	MOVLW	H'FF'
	MOVWF	DELAY1
D1
	MOVLW	H'FF'
	MOVWF	DELAY2
D2
	DECFSZ	DELAY2,F
	GOTO	D2
	DECFSZ	DELAY1,F
	GOTO	D1
	RETURN
BUTONARK
;{		;49993 cycles
	MOVLW	0x0E
	MOVWF	GECIK1
	MOVLW	0x28
	MOVWF	GECIK2
BUTONARK_0
	DECFSZ	GECIK1, F
	GOTO	$+2
	DECFSZ	GECIK2, F
	GOTO	BUTONARK_0
	GOTO	$+1	;3 cycles
	NOP		
	RETURN	;4 cycles (including call)	;}
	END
;------------Burak ÞEN tarafýndan yazýlmýþtýr--------------
;Ýnönü Üniversitesi Elektrik Elektronik Mühendisliði Öðrencisi